#!/usr/bin/env bash
# thi script show where point a subdomain

get_dig()
{
    echo -n "The subdomain $2 is a "
    dig "$1" | grep -A1 'ANSWER SECTION:' | awk '{if (NF >= 5 ) print $4 " record and points to " $5}'
}

if [[ "$#" -eq "2" ]]
then
    get_dig "$2.$1" "$2"

else
    declare -a subdomains
    subdomains[0]="www"
    subdomains[1]="lb-01"
    subdomains[2]="web-01"
    subdomains[3]="web-02"

    for i in "${subdomains[@]}"
    do
	get_dig "$i.$1" "$i"
    done
fi
