#!/usr/bin/env bash
# this script allows to install and configure nginx adding a http header Xserved
apt update
apt -y install nginx
ufw allow 'Nginx HTTP'
echo Holberton School > /var/www/html/index.html
sed -i "14i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
