#!/usr/bin/env bash
# Script that set the load balancer configurations for two servers
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy=1.8.\*

sudo echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backend-web\nbackend backend-web\n\tbalance roundrobin\n\tserver web1 35.229.39.180:80 check\n\tserver web2 34.74.15.139:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
