#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
for ((i = 1; i< 101; i++))
do
    if (( i % 5 == 0 && i % 3 == 0 ))
    then
	echo "FizzBuzz"
    elif (( i % 3 == 0 ))
    then
	echo "Fizz"
    elif (( i % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo "$i"
    fi
done
