#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with until
let 'i = 1'
while [ "$i" -le 10 ]
do
    echo "Holberton School"
    if [ $i = 9 ]
    then
	echo "hi"
    fi
    let 'i++'

done
