#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with hi in 9
let 'i = 1'
while [ "$i" -le 10 ]
do

    if [ "$i" = 4 ]
    then
	echo "bad luck"
    elif [ "$i" = 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let 'i++'

done
