#!/usr/bin/env bash
# This script is displaying "badluck" numbers for 3 countries, and the numbers to 1 to 20
let 'i = 1'
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    ;;
    esac
    let 'i++'
done
